### ISSUE TITLE
Simulate_character.py complains about module gym.spaces not having attribute 'Space'

### ISSUE THREAD

**Issue by ashley-holton** [namheegordonkim/l2cds#4]
When trying to run the character example, I assume I have to start by running simulate_character.py. I pulled this file and the others it needs up into the app/dart-env folder in the docker so that it can access the gym directory. When I run the file I get this:

root@1d0f10f26bdb:/app/dart-env# python3 simulate_character.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
failed to load pyqt5
Msg  [pydart2_api] init...
Msg  [pydart2_api] manager OK...
Msg  [pydart2_api] RI OK...
Msg  [pydart2_api] RI init OK...
Msg  [pydart2_api] Initialize pydart manager OK
/app/dart-env/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')
Traceback (most recent call last):
  File "simulate_character.py", line 9, in <module>
    from models import DummyNet
  File "/app/dart-env/models.py", line 11, in <module>
    from utils.utils import device
  File "/app/dart-env/utils/utils.py", line 10, in <module>
    from stable_baselines3.common.vec_env import SubprocVecEnv
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/__init__.py", line 3, in <module>
    from stable_baselines3.a2c import A2C
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/a2c/__init__.py", line 1, in <module>
    from stable_baselines3.a2c.a2c import A2C
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/a2c/a2c.py", line 7, in <module>
    from stable_baselines3.common.on_policy_algorithm import OnPolicyAlgorithm
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/on_policy_algorithm.py", line 8, in <module>
    from stable_baselines3.common.base_class import BaseAlgorithm
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/base_class.py", line 14, in <module>
    from stable_baselines3.common import utils
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/utils.py", line 19, in <module>
    from stable_baselines3.common.type_aliases import GymEnv, Schedule, TensorDict, TrainFreq, TrainFrequencyUnit
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/type_aliases.py", line 10, in <module>
    from stable_baselines3.common import callbacks, vec_env
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/callbacks.py", line 10, in <module>
    from stable_baselines3.common.evaluation import evaluate_policy
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/evaluation.py", line 8, in <module>
    from stable_baselines3.common.vec_env import DummyVecEnv, VecEnv, VecMonitor, is_vecenv_wrapped
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/vec_env/__init__.py", line 6, in <module>
    from stable_baselines3.common.vec_env.base_vec_env import CloudpickleWrapper, VecEnv, VecEnvWrapper
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 47, in <module>
    class VecEnv(ABC):
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines3/common/vec_env/base_vec_env.py", line 58, in VecEnv
    def __init__(self, num_envs: int, observation_space: gym.spaces.Space, action_space: gym.spaces.Space):
  File "/app/dart-env/gym/__init__.py", line 24, in __getattr__
    return getattr(gym.spaces, k)
AttributeError: module 'gym.spaces' has no attribute 'Space'

I have a suspicion it's something dependency related. I tried modifying the import gym.spaces statement in the __init__.py file of gym in a few different ways, but with no success. Any ideas?

**Comment by ashley-holton** [comment]
Awesome thank you so much! I'm actually trying to run stuff outside of the Dockerfile now so that I can visualize things, so is there any way I could get that requirements.txt file Steve was asking about? It'd be helpful for the step of the README that is to setup all the other requirements.

**Comment by namheegordonkim** [comment]
@ashley-holton okay, I added `requirements.txt`, but please note that DART must be installed at the OS level. See if you can use this to get Python packages.
