### ISSUE TITLE
Workflow For Corresponding a Walker with a Pendulum?

### ISSUE THREAD

**Issue by ashley-holton** [namheegordonkim/l2cds#5]
Hello, I'm trying to recreate what y'all did with making the pendulum and walker movements correspond, but I'm confused what scripts I should run in what order and with what parameters. I've gotten the simulate_character to work for the pendulum and walker2d_reg, but I'm confused where to go from there. I've also been able to visualize what I assume are the models y'all have already trained (the files in output). Thanks as always!

**Comment by namheegordonkim** [comment]
Hi @ashley-holton,

Thanks again for the patience with the sparse documentation. I'll update the README as soon as we get you up to speed.

# Simulate Characters

First thing you want to do is run `simulate_character.py`, which will (1) run an expert controller on the specified character and (2) simulate trajectories with multiple resets and action noise. At the end of `simulate_character.py`, the collected trajectories are saved in the `data/` directory. You will want to check out the `simulate_character.yml` file available inside the `config/` directory. You will want to do this for each character you want to correspond, e.g. `walker2d_reg`, `ostrich2d`, `pendulum2d`.

```
python simulate_character.py \
--config_name walker2d_reg \
--output_prefix ./data/walker2d_reg
```

```
python simulate_character.py \
--config_name ostrich2d \
--output_prefix ./data/ostrich2d
```

```
python simulate_character.py \
--config_name pendulum2d \
--output_prefix ./data/pendulum2d
```

# Learn Correspondence

Once these datapoints are collected, you will want to use the learning script to train the correspondence models. You will want to (1) change the config file, i.e. `configs/learn_correspondence.yml` so that `dataset_paths` are pointing to the correct trajectory files, and (2) run `learn_correspondence.py` like this:

```
python learn_correspondence.py \
--config_name walker2d_to_pendulum2d \
--output_prefix ./output/walker2d_to_pendulum2d
```

This will save model snapshots using the specified output prefix. You can change the number of training iterations as desired by modifying the `n_episodes` parameter in `configs/learn_correspondence.yml`.

# Visualize Correspondence

Once the loss has converged or training has finished, you will want to use the model snapshot files to visualize the simulated character and the corresponding poses of the counterpart. Again, you will want to (1) change the config file, i.e. `configs/visualize_correspondence.yml` and set `model_dicts_path` and `expert_dict_path` to point to the correct files. `model_dicts_path` is the model snapshots you've just created, and `expert_dict_path` is the expert controller trained via RL. Then (2) run `visualize_correspondence.py` like this:

```
python visualize_correspondence.py \
--config_name walker2d_to_pendulum2d \
--create_box  # if you want to test perturbations
```

**Comment by ashley-holton** [comment]
So I'm able to run the first two steps, but once I go to visualize, the window appears for a split second before immediately erroring out. It seems to be complaining about matrix dimensions. Here's the error:

python3 visualize_correspondence.py --config_name walker2d_to_pendulum2d
pygame 2.0.3 (SDL 2.0.16, Python 3.7.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Msg  [pydart2_api] init...
Msg  [pydart2_api] manager OK...
Msg  [pydart2_api] RI OK...
Msg  [pydart2_api] RI init OK...
Msg  [pydart2_api] Initialize pydart manager OK
/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.container.ModuleList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.activation.Tanh' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Identity' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/torch/serialization.py:671: SourceChangeWarning: source code of class 'models.ScalerWrapper' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.preprocessing.data module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.preprocessing. Anything that cannot be imported from sklearn.preprocessing is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 0.21.3 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
pydart initialization OK
Msg  [pydart2_api] worlds.size = 1
Msg  [pydart2_api] worlds.# skeletons = 2
/home/ashley/Documents/dart-env/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
set_camera: 0
set_camera: 2
Msg [pydart_api] /home/ashley/Documents/custom_dart_assets/pendulum2d.sdf
Msg  [pydart_api] parse as SDF (ext: .sdf)
Msg  [pydart_api] skel [/home/ashley/Documents/custom_dart_assets/pendulum2d.sdf]
Traceback (most recent call last):
  File "visualize_correspondence.py", line 202, in <module>
    render_one_way_correspondence(factory, model_dicts, expert_dict)
  File "visualize_correspondence.py", line 90, in render_one_way_correspondence
    state_encoder_source, state_decoder_target)
  File "/home/ashley/Documents/utils/walker2d_evaluate.py", line 106, in correspond
    input_state_scaled_tensor = input_state_scaler.forward(input_state_tensor).cpu()
  File "/home/ashley/Documents/models.py", line 277, in forward
    return torch.as_tensor(self.scaler.transform(x)).float().to(device)
  File "/home/ashley/anaconda3/envs/l2cds/lib/python3.7/site-packages/sklearn/preprocessing/_data.py", line 806, in transform
    X -= self.mean_
ValueError: operands could not be broadcast together with shapes (1,17) (2,) (1,17)


It also might be related to something I saw while running the learn_correspondence. After each episode it would say:
Episode x	Loss: ...
Episode x	Reward Mean: 0.000000	Std: 0.000000

I'm assuming the reward means and stds shouldn't be 0? What might be going wrong there if that's the case? 

Thanks!

**Comment by ashley-holton** [comment]
@namheegordonkim Just following up on this!

**Comment by namheegordonkim** [comment]
> `ValueError: operands could not be broadcast together with shapes (1,17) (2,) (1,17)`

17 is the number of state features of the walker2d character, and 2 is that of the pendulum. Sorry about this; I tested my code with walker-ostrich correspondence and wrote the instructions on walker-pendulum correspondence without double-checking. Just pushed a hotfix to the main branch. Thanks again for being so patient.

Also, please feel free to fork the codebase and make changes as you see fit. My intention with this code release was to show the rough pipeline as a supplement to the L2CDS paper, rather than to make a usable package. My colleagues and I used the code by commenting out and adding stuff as needed, and now this terrible habit came back to bite us :sweat_smile:
